export default {
  APPLICATION_INIT_REQUESTED: "APPLICATION_INIT_REQUESTED",
  APPLICATION_INIT_SUCCESS: "APPLICATION_INIT_SUCCESS",
  APPLICATION_INIT_FAILED: "APPLICATION_INIT_FAILED",

  USER_LOGIN_REQUESTED: "USER_LOGIN_REQUESTED",
  USER_LOGIN_SUCCESS:"USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILED:"USER_LOGIN_FAILED",

  USER_REGISTER_REQUESTED: "USER_REGISTER_REQUESTED",
  USER_REGISTER_SUCCESS:"USER_REGISTER_SUCCESS",
  USER_REGISTER_FAILED:"USER_REGISTER_FAILED"
};
