export default {
  APPLICATION_INIT_REQUESTED: "APPLICATION_INIT_REQUESTED",
  APPLICATION_INIT_SUCCESS: "APPLICATION_INIT_SUCCESS",
  APPLICATION_INIT_FAILED: "APPLICATION_INIT_FAILED",

  USER_LOGIN_REQUESTED: "USER_LOGIN_REQUESTED",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILED: "USER_LOGIN_FAILED",

  USER_REGISTER_REQUESTED: "USER_REGISTER_REQUESTED",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAILED: "USER_REGISTER_FAILED",

  APP_PAGECHANGER_REQUESTED: "APP_PAGECHANGER_REQUESTED",
  APP_PAGECHANGER_SUCCESS: "APP_PAGECHANGER_SUCCESS",

  APPLICATION_FETCH_COURSES_REQUESTED:"APPLICATION_FETCH_COURSES_REQUESTED",
  APPLICATION_FETCH_COURSES_SUCCESS:"APPLICATION_FETCH_COURSES_SUCCESS",
  APPLICATION_FETCH_COURSES_FAILED:"APPLICATION_FETCH_COURSES_FAILED",

  APPLICATION_FETCH_USERS_SUCCESS:"APPLICATION_FETCH_USERS_SUCCESS"


};
